# Generates a C++ source embedding database/migrations/*.sql as byte arrays.
# Usage: cmake -DMIGRATIONS_DIR=... -DOUTPUT=... -P cmake_embed.cmake
file(GLOB MIGRATION_FILES "${MIGRATIONS_DIR}/*.sql")
list(SORT MIGRATION_FILES)
set(BODY "#include \"db.hpp\"\nnamespace forge::cli {\n")
set(TABLE "")
set(COUNT 0)
foreach(FILE ${MIGRATION_FILES})
  get_filename_component(NAME ${FILE} NAME_WE)
  string(REGEX MATCH "^[0-9]+" VERSION_TEXT ${NAME})
  math(EXPR VERSION "${VERSION_TEXT}" OUTPUT_FORMAT DECIMAL)
  file(READ ${FILE} HEX HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX}")
  string(APPEND BODY "static const unsigned char migration_${COUNT}[] = {${BYTES}};\n")
  string(APPEND TABLE "  {${VERSION}, \"${NAME}\", migration_${COUNT}, sizeof(migration_${COUNT})},\n")
  math(EXPR COUNT "${COUNT} + 1")
endforeach()
string(APPEND BODY "const EmbeddedMigration embedded_migrations[] = {\n${TABLE}};\n")
string(APPEND BODY "const size_t embedded_migration_count = ${COUNT};\n}\n")
file(WRITE ${OUTPUT} "${BODY}")
