"use client";

import { useCallback, useEffect, useState } from "react";
import { ChessBoard } from "@/components/Board";
import { useEngine } from "./useEngine";

interface View {
  id: string;
  epd: string;
  side_to_move: string;
  in_check: boolean;
  legal_moves: number;
  children: { uci: string; id: string; epd: string }[];
}
interface Stored {
  first_ply: number;
  legal_moves: number;
  parents: { id: string; uci: string }[];
  children: { id: string; uci: string }[];
}

const START = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -";

export function ChessExplorer() {
  const [path, setPath] = useState<{ uci: string; epd: string }[]>([]);
  const [epd, setEpd] = useState(START);
  const [view, setView] = useState<View | null>(null);
  const [stored, setStored] = useState<Stored | "absent" | null>(null);
  const [input, setInput] = useState("");
  const [loadedDirectly, setLoadedDirectly] = useState(false);
  const { call, error } = useEngine();
  const load = useCallback(
    async (e: string) => {
      const v = await call<View>("chess.position", { epd: e });
      setView(v);
      setStored(null);
      if (!v) return;
      try {
        const r = await fetch(`/api/v1/explorer/chess/position/${v.id}`);
        setStored(r.ok ? ((await r.json()) as Stored) : "absent");
      } catch {
        setStored("absent");
      }
    },
    [call],
  );
  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- browser-only initialisation after hydration
    void load(epd);
  }, [epd, load]);
  const depth = loadedDirectly ? null : path.length;
  return (
    <div className="cols">
      <div>
        <ChessBoard epd={epd} />
        <div className="row-actions">
          <button
            className="btn quiet"
            type="button"
            disabled={path.length === 0}
            onClick={() => {
              const prev = path.slice(0, -1);
              setPath(prev);
              setEpd(prev.length ? prev[prev.length - 1].epd : START);
            }}
          >
            Back one move
          </button>
          <button
            className="btn quiet"
            type="button"
            onClick={() => {
              setPath([]);
              setLoadedDirectly(false);
              setEpd(START);
            }}
          >
            Start position
          </button>
        </div>
        <p className="caption">
          {path.length ? `Path: ${path.map((p) => p.uci).join(" ")}` : "The initial position."}
        </p>
        <label htmlFor="epd">Load a position (four-field EPD)</label>
        <input
          id="epd"
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder={START}
          style={{ width: "100%" }}
        />
        <div className="row-actions">
          <button
            className="btn quiet"
            type="button"
            onClick={() => {
              if (input.trim()) {
                setPath([]);
                setLoadedDirectly(true);
                setEpd(input.trim());
              }
            }}
          >
            Load
          </button>
        </div>
      </div>
      <div>
        {view ? (
          <>
            <dl className="kv" style={{ marginTop: 0 }}>
              <dt>Position id</dt>
              <dd className="mono">{view.id}</dd>
              <dt>EPD</dt>
              <dd className="mono">{view.epd}</dd>
              <dt>Depth</dt>
              <dd>
                {depth !== null
                  ? `${depth} plies from the start along this path`
                  : "unknown (loaded directly)"}
              </dd>
              <dt>Side to move</dt>
              <dd>
                {view.side_to_move}
                {view.in_check ? ", in check" : ""}
              </dd>
              <dt>Legal moves</dt>
              <dd className="num">{view.legal_moves}</dd>
              <dt>Dataset</dt>
              <dd>
                {stored === null
                  ? "checking…"
                  : stored === "absent"
                    ? "Not in the stored dataset; this view was computed on demand."
                    : `Stored. First reached at ply ${stored.first_ply}; ${stored.parents.length} stored parent${stored.parents.length === 1 ? "" : "s"}.`}
              </dd>
              <dt>Provenance</dt>
              <dd>
                Generated by the chess-perft/1 move generator, checked in CI against the standard perft
                suites.
              </dd>
            </dl>
            {stored && stored !== "absent" && stored.parents.length > 0 ? (
              <p className="muted">
                Other positions that lead here:{" "}
                {stored.parents
                  .slice(0, 6)
                  .map((p) => p.uci)
                  .join(", ")}
                {stored.parents.length > 6 ? ", …" : ""} (different move orders reaching one position are
                counted once).
              </p>
            ) : null}
            <h3>Legal moves</h3>
            {view.children.length === 0 ? (
              <p>{view.in_check ? "Checkmate." : "Stalemate."} There are no legal moves.</p>
            ) : (
              <div className="chips">
                {view.children.map((c) => (
                  <button
                    key={c.uci}
                    type="button"
                    className="chip"
                    onClick={() => {
                      setPath([...path, { uci: c.uci, epd: c.epd }]);
                      setEpd(c.epd);
                    }}
                  >
                    {c.uci}
                  </button>
                ))}
              </div>
            )}
          </>
        ) : null}
        {error ? <p className="error">That position could not be loaded: {error}</p> : null}
      </div>
    </div>
  );
}
